name: GitHub Deploy
run-name: Deploy new commit
on: [push]
jobs:
  deploy:
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    environment: environment
    steps:
      - run: |
            mkdir -p ~/.ssh
            echo $SSH_PRIVATE_KEY > ~/.ssh/key
            chmod 600 ~/.ssh/key
            echo "ssh.sanh.rip ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINDUlde+Uv6eCrX9BlYILVDYvZw6UTqPiobwlgdQKpb3" > ~/.ssh/known_hosts
            eval "$(ssh-agent -s)"
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
            ssh ssh.sanh.rip ls
